on: 
  - push
  - pull_request
jobs:
  compile-sketch:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - uses: arduino/compile-sketches@v1
        with: 
          sketch-paths: |
            - ./ArduioVehicleController/
          libraries: |
            - name: Adafruit MPU6050
            - name: Adafruit Unified Sensor
            - name: PCA9685 16-Channel PWM Driver Module Library

